version: '3.9'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"
      - "8002:8001"
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "${SERVER_PORT}:3300"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379