const strings = {
  title: "Joga",
  homeSubtitle:
    "Es una plataforma dedicada a impulsar a chefs emergentes y celebrar la gastronomía en todas sus formas. Nuestro espacio está diseñado para que puedas conocer a nuevos amigos o reencontrarte con aquellos que ya conoces. Aquí, cada comida se sirve al centro de la mesa, fomentando el compartir y celebrando la alegría de la sobremesa.",
  instagram: import.meta.env.VITE_INSTAGRAM || "https://www.instagram.com",
  whatsapp: import.meta.env.VITE_WHATSAPP || "https://wa.me",
  home: "Inicio",
  experiences: "Experiencias",
  events: "Eventos",
  products: "Productos",
  chefs: "Chefs",
  all: "Todos",
  search: "Buscar",
  locations: "Ubicaciones",
  remove: "Eliminar",
  schedule: "Agendar",
  add: "Agregar",
  added: "Agregado",
  typeOfFood: "Tipo de comida",
  aboutMe: "Sobre mí",
  goToCart: "Ir al carrito",
  continue: "Continuar",
  previous: "Anterior",
  yourCart: "Tu carrito",
  event: "Evento",
  date: "Fecha",
  quantity: "Cantidad",
  price: "Precio",
  total: "Total",
  confirm: "Confirmar",
  notRequired: "No requerido",
  upcommingEvents: "Próximos eventos",
  minParticipants: "Participantes mínimos",
  minParticipantsForEvent: "El mínimo de participantes para el evento debe ser de",
  extraFeeMessage: "Se aplicará un cargo adicional de ",
  selectADate: "Selecciona una fecha",
  scheduleExperience: "Agendar experiencia",
  createYourOwnEvent: "Crea tu propio evento",
  createExperience: "Crea tu experiencia",
  planExperience: "Planea tu experiencia",
  timeOfEvent: "¿A qué hora será tu evento?",
  timeOfEventSubtitle: "Selecciona la hora de inicio de tu evento.",
  locationOfEvent: "¿Dónde será tu evento?",
  locationOfEventSubtitle: "Agrega la dirección de tu evento.",
  createOwnEventSubtitle: "Personaliza cada detalle para que tu evento sea único e inolvidable. Elija entre una amplia gama de opciones, desde listas de invitados hasta ubicación entornos, asegurando que su evento refleje su estilo y visión perfectamente.",
  anyLastProduct: "¿Quieres agregar algún último producto?",
  numberOfParticipants: "¿Cuántas personas serán?",
  numberOfParticipantsSubtitle: "Selecciona el número de participantes que asistirán al evento.",
  selectNumberOfParticipants: "Selecciona el número de participantes",
  productsFromSelectedChefs: "Productos de los chefs seleccionados",
  pleaseCompleteTheSteps: "Por favor completa los pasos antes de continuar",
};

export default strings;
