const strings = {
  title: "Joga",
  homeSubtitle:
    "Es una plataforma dedicada a impulsar a chefs emergentes y celebrar la gastronomía en todas sus formas. Nuestro espacio está diseñado para que puedas conocer a nuevos amigos o reencontrarte con aquellos que ya conoces. Aquí, cada comida se sirve al centro de la mesa, fomentando el compartir y celebrando la alegría de la sobremesa.",
  instagram: import.meta.env.VITE_INSTAGRAM || "https://www.instagram.com",
  whatsapp: import.meta.env.VITE_WHATSAPP || "https://wa.me",
  home: "Inicio",
  experiences: "Experiencias",
  events: "Eventos",
  products: "Productos",
  chef: "Chef",
  chefs: "Chefs",
  close: "Cerrar",
  cancel: "Cancelar",
  all: "Todos",
  name: "Nombre",
  email: "Email",
  phone: "Teléfono",
  search: "Buscar",
  location: "Ubicación",
  comments: "Comentarios",
  locations: "Ubicaciones",
  remove: "Eliminar",
  schedule: "Agendar",
  add: "Agregar",
  added: "Agregado",
  typeOfFood: "Tipo de comida",
  aboutMe: "Sobre mí",
  addToCart: "Agregar al carrito",
  continue: "Continuar",
  previous: "Anterior",
  details: "Detalles",
  event: "Evento",
  date: "Fecha",
  quantity: "Cantidad",
  price: "Precio",
  total: "Total",
  subtotal: "Subtotal",
  time: "Hora",
  confirm: "Confirmar",
  confirmPurchase: "Confirmar compra",
  notRequired: "No requerido",
  upcommingEvents: "Próximos eventos",
  participants: "Participantes",
  minParticipants: "Participantes mínimos",
  minParticipantsForEvent:
    "El mínimo de participantes para el evento debe ser de",
  extraFeeMessage: "Se aplicará un cargo adicional de ",
  selectADate: "Selecciona una fecha",
  scheduleExperience: "Agendar experiencia",
  createYourOwnEvent: "Crea tu propio evento",
  createExperience: "Crea tu experiencia",
  planExperience: "Planea tu experiencia",
  viewDetails: "Ver detalles",
  reviewEvent: "Revisa tu evento",
  timeOfEvent: "¿En qué momento del día será tu evento?",
  timeOfEventSubtitle:
    "Elige entre desayuno, comida o cena según el horario de tu evento.",
  locationOfEvent: "¿Dónde será tu evento?",
  locationOfEventSubtitle: "Agrega la dirección completa de tu evento.",
  createOwnEventSubtitle:
    "Personaliza cada detalle para que tu evento sea único e inolvidable. Elija entre una amplia gama de opciones, desde listas de invitados hasta ubicación entornos, asegurando que su evento refleje su estilo y visión perfectamente.",
  anyLastProduct: "¿Quieres agregar algún último producto?",
  confirmDelete: "Confirmar eliminar",
  confirmDeleteSubtitle: "¿Estás seguro? Esta acción no se puede deshacer.",
  participantsInfo: "Cuéntanos sobre tu grupo",
  extraInfo: "¿Algo que debamos saber?",
  extraInfoSubtitle:
    "Cuéntanos si tienes alguna restricción alimentaria, preferencia especial o cualquier otro detalle.",
  extraInfoPlaceholder:
    "Ejemplo: “Sin gluten”, “Alérgico a los frutos secos”, “Prefiero opciones vegetarianas”...",
  numberOfParticipantsSubtitle:
    "Selecciona el número de participantes que asistirán al evento.",
  selectNumberOfParticipants: "Selecciona el número de participantes",
  productsFromSelectedChefs: "Productos de los chefs seleccionados",
  pleaseCompleteTheSteps: "Por favor completa los pasos antes de continuar",
  emptyCartMessage: "Tu carrito está vacío",
  missingData: "Se requiere completar la información",
  experienceNotAvailable: "La experiencia no está disponible en esa fecha",
  orderCreated: "Orden creada exitosamente, te contactaremos pronto",
};

export default strings;
