name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the project
      run: cd frontend && npm run build

    - name: Upload to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.5.0
      with:
        ftp-server: ${{ secrets.FTP_HOST }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/dist
        method: ftp
        dangerous-clean-slate: true  # Keeps previous files, change to true to remove old files
